"use client";

import React, { Suspense } from "react";
import dynamic from "next/dynamic";
import { GlassModule } from "../../components/GlassModule";

// Dynamic import of the WebGL Space Canvas to bypass SSR issues during Next.js builds
const SpaceUniverse = dynamic(
  () => import("../../components/SpaceUniverse").then((mod) => mod.SpaceUniverse),
  { ssr: false }
);

function NavLogo() {
  return (
    <div className="flex items-center gap-3">
      <svg width="34" height="34" viewBox="0 0 200 200" fill="none">
        <defs>
          <linearGradient id="navMGradient" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#00ffc8" />
            <stop offset="50%" stopColor="#0088ff" />
            <stop offset="100%" stopColor="#7a22ff" />
          </linearGradient>
        </defs>
        <path d="M40,40 L60,40 L85,85 L115,85 L140,40 L160,40 L160,150 L140,150 L140,75 L110,120 L90,120 L60,75 L60,150 L40,150 Z" fill="url(#navMGradient)" />
      </svg>
      <span className="logo font-['Bebas_Neue'] text-2xl tracking-[4px] text-white">MILLION<span className="text-[#00ffc8]">MINT</span></span>
    </div>
  );
}

export default function FounderPage() {
  return (
    <main className="min-h-screen bg-black text-white relative">
      
      {/* ── 3D WEBGL BACKGROUND LAYER ── */}
      <Suspense fallback={
        <div className="fixed inset-0 flex flex-col items-center justify-center bg-black z-50 font-mono text-xs text-[#00ffc8]">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#00ffc8] mb-4"></div>
          CONNECTING ORBITAL TELEMETRY...
        </div>
      }>
        <SpaceUniverse scrollProgress={5.5} />
      </Suspense>

      {/* ── PERSISTENT HUD NAVIGATION ── */}
      <nav>
        <a href="/" className="cursor-pointer hover:opacity-80 transition-opacity">
          <NavLogo />
        </a>
        <div className="nav-links hidden md:flex">
          <a href="/about">ABOUT</a>
          <a href="/roadmap">ROADMAP</a>
          <a href="/token">TOKEN</a>
          <a href="/whitepaper">WHITEPAPER</a>
          <a href="/founder" className="opacity-100 text-[#00ffc8]">FOUNDER</a>
        </div>
      </nav>

      {/* ── DOM CONTENT OVERLAY ── */}
      <div className="scroll-wrapper pt-32 pb-20">
        <div className="px-4 w-full flex justify-center">
          <GlassModule className="max-w-[1100px] pointer-events-auto">
            
            <div className="eyebrow">Founder Profile // Kalyan Chowdary</div>
            <h1 className="section-title text-center text-white mb-2" style={{ fontSize: "clamp(32px, 5vw, 60px)" }}>
              KALYAN CHOWDARY
            </h1>
            <p className="text-center font-mono text-xs text-[#f5c842] tracking-[4px] uppercase mb-10">
              Founder of Million Mint
            </p>

            <div className="space-y-8 font-mono text-sm leading-relaxed text-zinc-300">
              
              {/* SECTION 1: WHO I AM */}
              <div className="border-b border-[rgba(255,255,255,0.06)] pb-8">
                <h2 className="text-xl font-bold text-[#00ffc8] uppercase tracking-wider mb-4">1. Who I Am</h2>
                <p>
                  Kalyan Chowdary is the founder of Million Mint, a project focused on exploring digital ownership, virtual economies, and creator-first ecosystems powered by blockchain technology. With a background in software development and decentralized networks, Kalyan is passionate about building tools that empower users to control their own digital assets and spaces.
                </p>
              </div>

              {/* SECTION 2: WHY I STARTED MILLION MINT */}
              <div className="border-b border-[rgba(255,255,255,0.06)] pb-8">
                <h2 className="text-xl font-bold text-[#f5c842] uppercase tracking-wider mb-4">2. Why I Started Million Mint</h2>
                <p>
                  Million Mint began as an idea to give creators more control over the digital worlds they build. The project explores how ownership, governance, and digital economies can evolve beyond traditional centralized platforms. Kalyan noticed that modern digital platforms capture the majority of the value generated by their users, retaining control over assets and user monetization. Million Mint was started to design a spatial, open system where users have authentic sovereignty over their creations and can participate directly in the economies they help build.
                </p>
              </div>

              {/* SECTION 3: WHAT WE'RE BUILDING TODAY */}
              <div className="border-b border-[rgba(255,255,255,0.06)] pb-8">
                <h2 className="text-xl font-bold text-[#0088ff] uppercase tracking-wider mb-4">3. What We're Building Today</h2>
                <p>
                  Today, the project focuses on establishing the primary developer framework and spatial interface. We are building the Genesis Waitlist, the core client-side 3D orbital viewer, and developer APIs to test virtual asset registries. By deploying these systems on secure networks, we are setting up a playground where developers and creators can visualize district coordinates, simulate parcels, and test decentralized identity utilities in a low-latency environment.
                </p>
              </div>

              {/* SECTION 4: LONG-TERM VISION */}
              <div className="border-b border-[rgba(255,255,255,0.06)] pb-8">
                <h2 className="text-xl font-bold text-[#7a22ff] uppercase tracking-wider mb-4">4. Long-Term Vision</h2>
                <p>
                  Our long-term vision is to transition these experiments into a fully composable and self-governed network of virtual environments managed by decentralized autonomous organizations (DAOs). We aim to enable communities to define their own local rules, resource outputs, and trade pathways, proving that digital ownership and virtual GDP are sustainable alternatives to centralized gatekeepers.
                </p>
              </div>

              {/* SECTION 5: JOIN THE JOURNEY */}
              <div className="border-b border-[rgba(255,255,255,0.06)] pb-8">
                <h2 className="text-xl font-bold text-[#00ffc8] uppercase tracking-wider mb-4">5. Join the Journey</h2>
                <p>
                  We believe that building a digital civilization is a collaborative endeavor. Whether you are an engineer, 3D designer, economic strategist, or explorer, your feedback and participation help shape the foundation of Million Mint. Join our channels, test our early releases, and help us build the next generation of open digital worlds.
                </p>
              </div>

              {/* SECTION 6: PERSONAL STATEMENT */}
              <div>
                <h2 className="text-xl font-bold text-[#f5c842] uppercase tracking-wider mb-4">6. Personal Statement</h2>
                <blockquote className="border-l-2 border-[#f5c842] pl-4 italic text-zinc-400 my-6">
                  "For too long, the internet has operated on a landlord-tenant model where creators build value, only to be controlled by centralized platforms. Million Mint is an experiment in authentic digital ownership and community governance. Grounded in concrete execution, we invite you to explore this next generation of virtual systems with us."
                </blockquote>
                
                {/* Social links grid */}
                <div className="mt-8 pt-6 border-t border-[rgba(255,255,255,0.06)]">
                  <h4 className="text-white font-bold uppercase mb-4">Connect with the Founder:</h4>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <a href="https://x.com/kalyanchow369" target="_blank" rel="noopener noreferrer" className="p-4 border border-[rgba(255,255,255,0.06)] hover:border-[#00ffc8] bg-white/2 hover:bg-white/5 transition-all text-center">
                      <strong className="text-[#00ffc8] block mb-1">X / Twitter</strong>
                      <span className="text-xs text-zinc-500">@kalyanchow369</span>
                    </a>
                    <a href="https://github.com/kalyanastin" target="_blank" rel="noopener noreferrer" className="p-4 border border-[rgba(255,255,255,0.06)] hover:border-[#f5c842] bg-white/2 hover:bg-white/5 transition-all text-center">
                      <strong className="text-[#f5c842] block mb-1">GitHub</strong>
                      <span className="text-xs text-zinc-500">github.com/kalyanastin</span>
                    </a>
                    <a href="https://t.me/millionmint" target="_blank" rel="noopener noreferrer" className="p-4 border border-[rgba(255,255,255,0.06)] hover:border-[#0088ff] bg-white/2 hover:bg-white/5 transition-all text-center">
                      <strong className="text-[#0088ff] block mb-1">Telegram</strong>
                      <span className="text-xs text-zinc-500">t.me/millionmint</span>
                    </a>
                  </div>
                </div>
              </div>

            </div>

            {/* Back button */}
            <div className="mt-12 pt-6 border-t border-[rgba(255,255,255,0.06)] flex justify-between items-center">
              <span className="text-[10px] font-mono text-zinc-500">SYSTEM SECURE STATUS: ONLINE</span>
              <a href="/" className="btn-gold !mt-0 !py-3 !px-8 text-xs">
                Back To Terminal
              </a>
            </div>

          </GlassModule>
        </div>
      </div>

      {/* FOOTER SECTION */}
      <footer className="w-full py-12 px-6 border-t border-[rgba(255,255,255,0.03)] bg-black/60 backdrop-blur-md flex flex-col md:flex-row justify-between items-center gap-6 pointer-events-auto relative z-10">
        <div className="flex flex-col items-center md:items-start gap-2">
          <NavLogo />
          <p className="text-[10px] font-mono text-zinc-500 mt-1">
            © {new Date().getFullYear()} Million Mint. All rights reserved.
          </p>
        </div>
        <div className="flex gap-6 font-mono text-xs text-zinc-400">
          <a href="https://x.com/kalyanchow369" target="_blank" rel="noopener noreferrer" className="hover:text-[#00ffc8] transition-colors">X (Twitter)</a>
          <a href="https://t.me/millionmint" target="_blank" rel="noopener noreferrer" className="hover:text-[#00ffc8] transition-colors">Telegram</a>
          <a href="https://github.com/kalyanastin/million-mint-ai-terminal" target="_blank" rel="noopener noreferrer" className="hover:text-[#00ffc8] transition-colors">GitHub</a>
          <a href="/sitemap.xml" className="hover:text-[#00ffc8] transition-colors">Sitemap</a>
        </div>
      </footer>

    </main>
  );
}
